# Generated by Django 3.2 on 2021-04-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210419_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liketoanswer',
            old_name='question',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='liketoanswer',
            old_name='vote',
            new_name='is_liked',
        ),
        migrations.RenameField(
            model_name='liketoquestion',
            old_name='vote',
            new_name='is_liked',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/avatar.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
