# Generated by Django 3.2 on 2021-04-20 09:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210420_0841'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
