# Generated by Django 3.2 on 2021-04-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210420_0909'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
            ],
        ),
    ]
