# Generated by Django 3.2 on 2021-04-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_question_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num',
        ),
    ]
