# Generated by Django 3.2 on 2021-05-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_question_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
